# Generated by Django 4.0.5 on 2022-07-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
